"""Claude Vision quality scorer (Pillar 2: tool layer).

Scores a generated image against the brief using claude-opus-4-8 with structured
outputs (output_config.format). Because the response is schema-constrained, the
JSON is always valid — no "ask for JSON ONLY / fall back to 5" parsing. The
structured critique (composition, style_match, issues, suggested_fix) is what
feeds the retry loop and the LangSmith score history.
"""
from __future__ import annotations

import base64
import json
import time

import anthropic
import requests

MAX_ATTEMPTS = 3

VISION_MODEL = "claude-opus-4-8"

# Response is constrained to this schema by output_config.format.
SCORE_SCHEMA = {
    "type": "object",
    "properties": {
        "score": {"type": "integer"},
        "composition": {"type": "string"},
        "style_match": {"type": "string"},
        "issues": {"type": "array", "items": {"type": "string"}},
        "suggested_fix": {"type": "string"},
    },
    "required": ["score", "composition", "style_match", "issues", "suggested_fix"],
    "additionalProperties": False,
}

SYSTEM = (
    "You are a meticulous creative director at a generative-AI content studio. "
    "Score the image strictly against the brief on a 1-10 scale, where 8 or above "
    "means client-ready. Judge composition, adherence to the brief and style, and "
    "technical quality (anatomy, artifacts, stray text). Be specific and honest — "
    "do not inflate scores. `suggested_fix` should be a concrete prompt change."
)

SYSTEM_AD = (
    "You are an advertising creative director reviewing a product ad generated by "
    "placing a real product photo into an AI scene. Score 1-10, where 8+ means "
    "ready to publish. Judge, in order of importance: (1) the product is clearly "
    "visible, undistorted, and faithful to the described product; (2) the scene "
    "looks like a premium, realistic ad (lighting, shadows, and the product sit "
    "naturally together — no obvious cut-out/floating look); (3) commercial appeal "
    "and on-brand mood; (4) no artifacts, stray text, or warped edges. Be honest "
    "and specific. `suggested_fix` should be a concrete change to the scene prompt."
)

_client: anthropic.Anthropic | None = None


def _get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env
    return _client


def _fetch_as_base64(image_url: str) -> tuple[str, str]:
    """Download the image ourselves and return (media_type, base64_data).

    We fetch the bytes rather than passing a URL source so scoring doesn't depend
    on the remote host allowing Anthropic's fetcher (robots.txt), and so signed /
    expiring URLs (e.g. Replicate delivery links) work reliably.
    """
    r = requests.get(image_url, timeout=30)
    r.raise_for_status()
    media_type = r.headers.get("content-type", "image/png").split(";")[0].strip()
    return media_type, base64.standard_b64encode(r.content).decode("utf-8")


def score_image(image_url: str, original_brief: str, mode: str = "text") -> dict:
    """Return {score, composition, style_match, issues, suggested_fix}."""
    system = SYSTEM_AD if mode == "ad" else SYSTEM
    ref_label = "Product description" if mode == "ad" else "Creative brief"
    task = "Score this product ad." if mode == "ad" else "Score this image."
    media_type, data = _fetch_as_base64(image_url)

    last_err: Exception | None = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            resp = _get_client().messages.create(
                model=VISION_MODEL,
                max_tokens=1024,
                system=system,
                output_config={"format": {"type": "json_schema", "schema": SCORE_SCHEMA}},
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": media_type,
                                    "data": data,
                                },
                            },
                            {
                                "type": "text",
                                "text": f"{ref_label}:\n{original_brief}\n\n{task}",
                            },
                        ],
                    }
                ],
            )
            break
        except anthropic.APIStatusError as e:
            last_err = e
            if e.status_code == 529 and attempt < MAX_ATTEMPTS:
                time.sleep(2 ** (attempt - 1))
                continue
            raise
    else:
        raise RuntimeError(f"score_image failed after {MAX_ATTEMPTS} attempts: {last_err}")

    # Structured outputs guarantee the first text block is schema-valid JSON.
    text = next((b.text for b in resp.content if b.type == "text"), None)
    if text is None:
        raise RuntimeError("vision scorer returned no text block")
    return json.loads(text)
